//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;


namespace _1101664.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablesongs1101664
    {
        [Required]
        [Display(Name ="編號")]
        public int Id { get; set; }

        [Required]
        [Display(Name = "歌名")]
        public string songname { get; set; }

        [Display(Name = "歌手")]
        public string singer { get; set; }

        [Display(Name = "作曲")]
        public string author { get; set; }

        [Display(Name ="時長")]
        public Nullable<System.TimeSpan> time { get; set; }
    }
}
