//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace _1101664.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablelogins1101664
    {
        [Required]
        [Display(Name ="帳號:")]
        public int account { get; set; }
        
        [Required]
        [Display(Name = "密碼:")]
        public string password { get; set; }

        [Display(Name = "暱稱:")]
        public string name { get; set; }

        [Display(Name = "信箱:")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [Display(Name = "電話:")]
        public string phonenumber { get; set; }

        [Display(Name = "地址:")]
        public string address { get; set; }
    }
}
