//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace _1101664.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableAllroles1101664
    {
        [Required]
        [Display(Name = "編號")]
        public int Id { get; set; }
        
        [Required]
        [Display(Name = "名前")]
        public string name { get; set; }

        [Display(Name = "物種")]
        public string category { get; set; }

        [Display(Name ="年齡")]
        public Nullable<int> age { get; set; }

        [Display(Name = "身高")]
        public Nullable<int> height { get; set; }

        [Display(Name = "能力")]
        public string ability { get; set; }

        [Display(Name = "職業")]
        public string attribute { get; set; }
    }
}
